name: Build Angular App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22.17.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          check-latest: true
          cache: 'npm'

      - name: Confirm Node & npm version
        run: |
          node -v
          npm -v

      - name: Upgrade npm to latest (v10+)
        run: npm install -g npm@latest

      - name: Install dependencies (clean)
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build Angular app
        run: npm run build -- --configuration production
