name: Build & Deploy Angular 20 to Azure Static Web Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22.17.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          check-latest: true
          cache: 'npm'

      - name: Confirm Node & npm version
        run: |
          node -v
          npm -v

      - name: Upgrade npm to latest (v10+)
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"                                 # Angular project root
          output_location: "dist/my-app"       # Replace with actual folder name
